spring:
  main:
    web-application-type: reactive
  data:
    redis:
      host: host.docker.internal
      port: 6379
      password: ${redis.password}
  cache:
    type: redis
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    enabled: true
    sampling:
      probability: 1.0