spring:
  data:
    mongodb:
      authentication-database: admin
      username: ${mongodb.username}
      password: ${mongodb.password}
      database: data_db
      port: 27017
      host: host.docker.internal
    redis:
      host: host.docker.internal
      port: 6379
      password: ${redis.cache.password}
  cache:
    type: redis
management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    enabled: true
    sampling:
      probability: 1.0